# Generated by Django 4.2.19 on 2025-03-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project_projectfile_delete_dataresource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectfile",
            name="web_path",
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "文本"),
                    ("image", "图像"),
                    ("audio", "音频"),
                    ("video", "视频"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
